import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  // Primary key: UUID string generated by the application layer (crypto.randomUUID())
  id: text('id').primaryKey(),

  // Email: login credential, globally unique, format validated by backend
  email: text('email').notNull().unique(),

  // Nickname: display name, 2-20 characters, no pure whitespace
  nickname: text('nickname').notNull(),

  // Password hash: stored as bcrypt hash, plaintext is forbidden
  passwordHash: text('password_hash').notNull(),

  // Privacy policy agreement timestamp (Unix milliseconds), required at registration
  agreedAt: integer('agreed_at').notNull(),

  // Record creation timestamp (Unix milliseconds)
  createdAt: integer('created_at').notNull(),

  // Record last-updated timestamp (Unix milliseconds)
  updatedAt: integer('updated_at').notNull(),
});

// Expose the _ accessor expected by Drizzle-aware tooling and tests.
// Drizzle stores metadata in Symbols at runtime; the _ property was a
// TypeScript-only type-level construct in older versions. We surface it
// here so that runtime code can use users._.name and users._.columns.
Object.defineProperty(users, '_', {
  get() {
    return {
      name: this[Symbol.for('drizzle:Name')],
      columns: this[Symbol.for('drizzle:Columns')],
    };
  },
  enumerable: false,
  configurable: true,
});
