import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

/**
 * users table - stores user account data
 *
 * Fields:
 * - id: UUID string, application-generated via crypto.randomUUID()
 * - email: unique login identifier, validated on backend
 * - nickname: display name, 2-20 characters, trimmed before storage
 * - passwordHash: bcrypt hash (saltRounds=10), never plaintext
 * - agreedAt: Unix millisecond timestamp of privacy policy consent
 * - createdAt: Unix millisecond timestamp of account creation
 * - updatedAt: Unix millisecond timestamp of last update
 */
export const users = sqliteTable('users', {
  // Primary key: UUID string, generated by application layer (crypto.randomUUID())
  id: text('id').primaryKey(),

  // Email: login credential, globally unique, format validated by backend
  email: text('email').notNull().unique(),

  // Nickname: display name, 2-20 characters, no pure whitespace
  nickname: text('nickname').notNull(),

  // Password hash: bcrypt hash, saltRounds=10; plaintext is forbidden
  passwordHash: text('password_hash').notNull(),

  // Privacy policy agreement timestamp (Unix milliseconds), required at registration
  agreedAt: integer('agreed_at').notNull(),

  // Account creation timestamp (Unix milliseconds), set by application on INSERT
  createdAt: integer('created_at').notNull(),

  // Last update timestamp (Unix milliseconds), maintained by application on UPDATE
  updatedAt: integer('updated_at').notNull(),
});
