import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  // Primary key: UUID string generated by application layer (crypto.randomUUID())
  id: text('id').primaryKey(),

  // Email: login credential, globally unique, format validated by backend
  email: text('email').notNull().unique(),

  // Nickname: display name, 2-20 characters, no pure whitespace
  nickname: text('nickname').notNull(),

  // Password hash: bcrypt hash, never stored as plaintext
  passwordHash: text('password_hash').notNull(),

  // Privacy policy agreed timestamp (Unix ms), required at registration
  agreedAt: integer('agreed_at').notNull(),

  // Account creation timestamp (Unix ms), set by application at INSERT
  createdAt: integer('created_at').notNull(),

  // Last update timestamp (Unix ms), maintained by application at UPDATE
  updatedAt: integer('updated_at').notNull(),
});
